### ISSUE TITLE
I got a problem with Dat archives, please help

### ISSUE THREAD

**Issue by tribu2015** [BenDol/otclient-candybot#35]
I make the client for custom ot, but when i put my custom tibia.dat  from the ot, its say unable to load tibia.dat file please put a correct tibia.dat", what i can do ?, to fix this dat so candybot can work for me, thanks

**Comment by gugugpg** [comment]
I dont know speak  English.  Sorry :/
Em 13/11/2015 00:49, "tribu2015" <notifications@github.com> escreveu:
