### ISSUE TITLE
Cavebot

### ISSUE THREAD

**Issue by b3liar** [BenDol/otclient-candybot#37]
Are you going to add cavebot with waypoints and lua actions like "open itemid" ?

**Comment by b3liar** [comment]
and you should add best thing ever in bots "Hotkeys" from elfbot custom lua scripts :)

**Comment by BenDol** [comment]
Right now the development is on hold. I am welcoming contributions from the community however.

**Comment by b3liar** [comment]
Thanks for reply :)
